package com.example.fitnessmanagementsystem.model;

import jakarta.persistence.*;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * Entity class representing a schedule in the fitness management system.
 * This class maps to a database table and contains information about
 * schedules assigned to members and trainers.
 */
@Entity
@Getter
@Setter
@Data
public class Schedule {

    /**
     * Unique identifier for the schedule.
     * It is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The member associated with this schedule.
     * This establishes a many-to-one relationship with the Member entity.
     */
    @ManyToOne
    private Member member;

    /**
     * The trainer associated with this schedule.
     * This establishes a many-to-one relationship with the Trainer entity.
     */
    @ManyToOne
    private Trainer trainer;

    /**
     * The start time of the scheduled activity.
     */
    private LocalDateTime startTime;

    /**
     * The end time of the scheduled activity.
     */
    private LocalDateTime endTime;

    /**
     * Description of the activity scheduled.
     */
    private String activity;
}
